# Generated by Django 4.1 on 2022-08-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Meme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("tags", models.TextField()),
                ("image", models.TextField()),
                ("topText", models.TextField()),
                ("bottomText", models.TextField()),
                ("detail", models.TextField()),
                ("thumb", models.TextField()),
                ("rank", models.TextField()),
            ],
        ),
    ]
