# Generated by Django 4.1 on 2022-08-23 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("meme", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topText", models.TextField()),
                ("dateCreated", models.DateField(auto_now=True)),
                ("bottomText", models.TextField()),
                (
                    "memeID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="meme.meme"
                    ),
                ),
            ],
        ),
    ]
