# Generated by Django 4.1 on 2022-08-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meme", "0002_submission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="dateCreated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
