# Generated by Django 4.1 on 2022-08-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meme", "0004_alter_meme_bottomtext_alter_meme_detail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meme",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
