# Generated by Django 4.1 on 2022-08-24 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("meme", "0007_alter_submission_memeid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meme",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="memeID",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="meme.meme"
            ),
        ),
    ]
