# Generated by Django 4.1 on 2022-08-24 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("meme", "0009_alter_submission_memeid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meme",
            name="bottomText",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="meme",
            name="detail",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="meme",
            name="name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="meme",
            name="rank",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="meme",
            name="thumb",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="meme",
            name="topText",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="memeID",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="meme.meme"
            ),
        ),
    ]
