# Generated by Django 4.1 on 2022-08-24 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("meme", "0010_alter_meme_bottomtext_alter_meme_detail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="memeID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="meme.meme"
            ),
        ),
    ]
