# Generated by Django 4.1 on 2022-08-24 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meme", "0011_alter_submission_memeid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="submission",
            old_name="memeID",
            new_name="meme",
        ),
    ]
