# Generated by Django 4.1 on 2022-08-24 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meme", "0012_rename_memeid_submission_meme"),
    ]

    operations = [
        migrations.RenameField(
            model_name="submission",
            old_name="meme",
            new_name="memeID",
        ),
    ]
