# Generated by Django 4.1 on 2022-08-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meme", "0013_rename_meme_submission_memeid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meme",
            name="image",
            field=models.ImageField(upload_to="memes/%Y/%M/%D/"),
        ),
    ]
